### ISSUE TITLE
no CMakeLists.txt

### ISSUE THREAD

**Issue by martijncassels** [ahmetozlu/VehicleDetectionAndCounting#1]
Could you create a CMakeLists.txt for the new cmake versions?

(running on cmake 3.9.2)

**Comment by ahmetozlu** [comment]
CMakeLists.txt was added, could you check it?

You can follow the commands which are given in project ReadMe(under Installation heading) to compile the project by using CMake.

**Comment by martijncassels** [comment]
thnx! will check and let you know

**Comment by martijncassels** [comment]
works, but did you use OpenCV win-pack or the source from github and built it with cmake as well?
I get a lot of linking issues (LNK1104) in VS 2017
